# mcp_runtime/tier1_tools.py

TIER1_TOOL_NAMES = {
    "fabric_get_fabrics",
    "fabric_get_fabric",
    "fabric_validate_fabric",
    "fabric_get_fabric_setting",
    "fabric_get_fabrics_health",
    "fabric_get_fabric_health", 
    "fabric_get_health", 
    "fabric_get_fabrics_errors",
    "fabric_get_fabric_errors",
    "fabric_get_devices",
    "fabric_get_physical_topology",
    "fabric_get_topology_overlay",
    "fabric_get_underlay_topology",
    "fabric_get_overlay_topology",
    "fabric_validate_physical_topology",
    "fabric_get_service_locks",
    "fabric_get_running_config",
    "fabric_get_execution_list",
    "fabric_get_execution_get",
    "fabric_get_event_history_list",
    "fabric_get_config_show",

    "inventory_getswitches",
    "inventory_switch_inventory_summary",
    "inventory_switch_inventory_info"

    "inventory_get_rma_history",
    "inventory_get_rma_detail",
    "inventory_get_tpvm_upgrade_status",
    "inventory_get_firmware_download_status",
    "inventory_get_firmware_download_history",
    "inventory_get_firmware_download_operation_history",
    "inventory_get_device_inventory_structure",
    "inventory_get_device_inventory_summary",
    "inventory_get_device_inventory_info",
    "inventory_get_device_inventory_ports",
    "inventory_get_device_inventory_export",
    "inventory_get_getting_started",
    "inventory_get_rma_historys",
    "inventory_get_rma_detail",
    "inventory_get_multi_tpvm_upgrade_status",
    "inventory_get_tpvm_upgrade_status",
    "inventory_get_tpvm_list",
    "inventory_get_switch_setting",
    "inventory_get_switch_health_status",
    "inventory_get_firmware_download_status",
    "inventory_get_firmware_download_history_status",
    "inventory_get_firmware_download_operation_history",
    "inventory_get_prepared_switches",
    "inventory_get_device_tacacs_configs",
    "inventory_get_device_tacacs_config",
    "inventory_get_aaa_config",
    "inventory_get_interfaces",
    "inventory_list_breakout_ports",
    "inventory_get_port_channels",
    "inventory_get_lldp_data",
    "inventory_get_links",
    "inventory_get_vlan_ss",
    "inventory_get_mirror_sessions",
    "inventory_get_drift_reconcile_historys",
    "inventory_get_drift_reconcile_detail",
    "inventory_get_config_backup_historys",
    "inventory_get_config_backup_detail",
    "inventory_get_config_replay_historys",
    "inventory_get_config_replay_detail",
    "inventory_get_v_es",
    "inventory_get_router_bgp",
    "inventory_get_mct_management_cluster",
    "inventory_get_mct_cluster_configuration",
    "inventory_get_mct_cluster_clients",
    "inventory_get_lif",
    "inventory_get_evpn_instance",
    "inventory_get_pseudowire_profile",
    "inventory_get_bridge_domain",
    "inventory_get_overlay_gateway",
    "inventory_get_tunnel",
    "inventory_get_vrf",
    "inventory_get_vrrp",
    "inventory_get_router_pim",
    "inventory_get_ip_prefix_list",
    "inventory_get_route_map",
    "inventory_get_community_list",
    "inventory_get_ext_community_list",
    "inventory_get_policy",
    "inventory_get_execution_get",
    "inventory_get_execution_list",
    "inventory_get_running_config",
    "inventory_get_key_value_list",
    "inventory_get_value_for_key",
    "inventory_get_firmware_hosts",
    "inventory_get_firmware_host_protocols",
    "inventory_get_firmware_host",
    "inventory_get_device_details",
    "inventory_get_device_adapter_status",
    "inventory_get_devices_lock_status",
    "inventory_get_service_lock_status",
    "inventory_get_fwdl_in_progress_devices",
    "inventory_get_device_inventory_structure",
    "inventory_get_device_inventory_ports",
    "inventory_get_device_certificates_expiry",
    "inventory_get_dsc_historys",
    "inventory_get_device_state",
    "inventory_get_dsc_detail",
    "inventory_get_health",
    "inventory_get_ntp_servers",
    "inventory_get_ntp_disable",
    "inventory_get_snmp_communities",
    "inventory_get_snmp_users",
    "inventory_get_snmp_hosts",
    "inventory_get_snmp_groups",
    "inventory_get_snmp_views",
    "inventory_get_snmp_use_vrfs",
    "inventory_get_device_timezone",
    "inventory_get_supported_device_timezones",
    "inventory_get_bindings",
    "inventory_get_threshold_monitors",
    "inventory_get_all_locations",
    "inventory_get_download_locations",
    "inventory_get_secure_settings",

    "auth_validate_token",
    "auth_get_token_expiry",
    "auth_get_all_token_expiry",
    "auth_get_clients",
    "auth_get_client_by_name",
    "auth_get_execution",
    "auth_get_executions",
    "auth_get_api_key",
    "auth_get_ldap_details",
    "auth_get_ldap_list",
    "auth_get_exec_logs",
    "auth_get_role_mappings",
    "auth_get_tacacs_by_host",
    "auth_get_authentication_summary_list",
    "auth_get_auth_preferences",
    "auth_get_active_user_by_type",
    "auth_get_user_by_name",
    "auth_get_host_users",
    "auth_get_active_host_users",

    "system_get_feature_settings",
    "system_get_settings",
    "system_get_running_config",
    "system_get_health_status",
    "system_get_supportsave_list",
    "system_get_supportsave_status",
    "system_get_executions",
    "system_get_execution",
    "system_get_last_execution_diagnostic",
    "system_get_logging_customization",
    "system_get_file_download",


    "monitor_get_service_status",
    "monitor_get_k3s_status",
    "monitor_get_k3s_nodes",
    "monitor_get_k3s_pods",
    "monitor_get_k3s_resources",
    "monitor_get_deployment_config",
    "monitor_get_all_status",
    "monitor_get_maria_db_info",
    "monitor_get_gluster_fs_info",
    "monitor_get_keep_alived_info",
    "monitor_get_efa_status",
    "monitor_get_redeploy_status",
    "monitor_get_certificate_expiry",
    "monitor_get_support_save",
    "monitor_get_support_save_list",
    "monitor_get_backup_list",
    "monitor_get_restore_status",
    "monitor_get_restore_history",
    "monitor_get_sub_interface",
    "monitor_get_static_i_ps",
    "monitor_get_virtual_route",
    "monitor_get_health",
    "monitor_get_health_detail",
    "monitor_get_health_inventory",
    "monitor_get_host_users",
   

   "notification_get_subscribers",
   "notification_get_subscriber",
   "notification_get_executions",


   "faultmanager_get_health",
   "faultmanager_get_alert_inventory",
   "faultmanager_get_alert_history",
   "faultmanager_get_alarm_inventory",
   "faultmanager_get_alarm_history",
   "faultmanager_get_alarm_summary",


   "snmp_get_health",
   "snmp_get_trap_subscribers",
   "snmp_get_executions",
   "snmp_get_execution",


   "tenant_get_health",
   "tenant_get_tenants",
   "tenant_get_tenant",
   "tenant_get_portchannels",
   "tenant_get_portchannel",
   "tenant_get_bgp_peer_operational",
   "tenant_get_bgp_peers",
   "tenant_get_bgp_peer",
   "tenant_get_mirror_sessions",
   "tenant_get_vrfs",
   "tenant_get_vrf_static_routes",
   "tenant_get_vrf",
   "tenant_get_vrf_route_target",
   "tenant_get_vrf_static_routes_bfd",
   "tenant_get_vrf_error",
   "tenant_get_endpoint_groups",
   "tenant_get_endpoint_group",
    "tenant_get_endpoint_group_error",
    "tenant_get_bgp_service_peer_groups",
    "tenant_get_bgp_service_peer_group",
    "tenant_get_mirror_service_session",
    "tenant_get_execution_get",
    "tenant_get_execution_list",
    "tenant_get_running_config",
    "tenant_get_event_history_list",
    "tenant_get_locks",


   "rbac_validate_authorization",
   "rbac_validate_tenant_authorization",
   "rbac_get_authorized_tenants",
   "rbac_get_role",
   "rbac_get_roles",
   "rbac_get_executions",
   "rbac_get_execution_detail",
   "rbac_get_user_permissions",


   "licensing_get_health",
   "licensing_get_licenses",


   "vcenter_get_vcenters",
   "vcenter_get_vcenter_details",
   "vcenter_get_esxi_details",
   "vcenter_get_tenant_details",
   "vcenter_get_events",
   "vcenter_get_physical_links",
   "vcenter_get_virtual_links",
   "vcenter_get_unconnected_pnics",
   "vcenter_get_executions",


   "hyperv_get_servers",
   "hyperv_get_physical_links",
   "hyperv_get_virtual_links",
   "hyperv_get_service_settings",
   "hyperv_get_executions",





    
}

